# Generated by Django 5.2.7 on 2025-10-13 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coorientador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coorientador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='historicalcoorientador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalcoorientador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='historicalorientador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalorientador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='orientador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orientador',
            name='nome',
        ),
        migrations.AddField(
            model_name='coorientador',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo_usuario': 'PROF'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_coorientador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcoorientador',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'tipo_usuario': 'PROF'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorientador',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'tipo_usuario': 'PROF'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orientador',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo_usuario': 'PROF'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_orientador', to=settings.AUTH_USER_MODEL),
        ),
    ]
