# Generated by Django 4.2.7 on 2025-10-13 01:23

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_coorientador_email_remove_coorientador_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmonografia',
            name='arquivo_pdf',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[core.validators.validate_pdf_file, core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='monografias/', validators=[core.validators.validate_pdf_file, core.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('READ', 'Visualização'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('objeto', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-timestamp'],
            },
        ),
    ]
